
import mustache from "mustache";
import "hardhat-deploy";
import { task } from "hardhat/config";
import path from "path";

import { stripHexPrefix } from "ethereumjs-util";

// deployment and parametrisation done via a gnosis safe multisig 
// by submitting a json file generated by this script to the transaction builder

type voltzTemplateDataSingular = {
    token: string;
    voltzVaults: {
        marginEngine: string;
        initializeParams: VaultInitialParam;
    }[],
    vaultStrategyParams: {
        last: boolean;
        params: VaultStrategyParam;
    }[];
    strategy: string;
    erc20VaultAddress: string;
    voltzVaultAddresses: {
        last: boolean;
        address: string;
    }[];
    erc20RootVaultNFT: number;
    vaultNFTs: {
        last: boolean;
        tokenId: number;
    }[];
    vaultCap: string;
};

type voltzTemplateData = {
    owner: string;

    vaultRegistry: string;
    voltzVaultGovernance: string;
    erc20VaultGovernance: string;
    erc20RootVaultGovernance: string;
    masterStrategy: string;
    voltzVaultHelperSingleton: string;
    rebalancer: string;

    data: {
        vaultData: voltzTemplateDataSingular,
        last: boolean;
    }[];
};

const writeVoltzDeployments = (
    data: voltzTemplateData
): void => {
    // Get external template with fetch
    const fs = require("fs");

    const template = fs.readFileSync(
        path.join(__dirname, "json_templates/VoltzDeployment.json.mustache"),
        "utf8"
    );
    const output = mustache.render(template, data);

    const jsonDir = path.join(__dirname, "jsons");
    const outFile = path.join(
        jsonDir,
        `1-VoltzDeployment.json`
    );
    if (!fs.existsSync(jsonDir)) {
        fs.mkdirSync(jsonDir);
    }
    fs.writeFileSync(outFile, output);

    console.log("Output written to ", outFile.toString());
};

type VaultInitialParam = {
    tickLower: number,
    tickUpper: number,
    leverageWad: string,
    marginMultiplierPostUnwindWad: string,
};

type VaultStrategyParam = {
    sigmaWad: string;
    maxPossibleLowerBoundWad: string;
    proximityWad: string;
    weight: string;
};

type VaultSetup = {
    marginEngine: string;
    vaultInitialParam: VaultInitialParam;
    vaultStrategyParam: VaultStrategyParam;
}

type NetworkSetup = { [key: string]: VaultSetup };

const setup: { [key: string]: NetworkSetup } = {
    mainnet: {
        // USDC
        'aUSDC_v12': {
            marginEngine: '0xfa2ad0f34bc701ba0d65740bc3f833d5aa2b6f3d',
            vaultInitialParam: {
                tickLower: -5880,
                tickUpper: -1860,
                leverageWad: "150000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "300000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "75000000000000000",
                weight: "85",
            }
        },

        'borrow_aUSDC_v2': {
            marginEngine: '0xd6f2ef8e7f5917beda41136cb4a50e8be7735b4f',
            vaultInitialParam: {
                tickLower: -10800,
                tickUpper: -8520,
                leverageWad: "150000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "300000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "75000000000000000",
                weight: "15",
            }
        },

        // ETH
        'stETH_v3': {
            marginEngine: '0x3dd093822661bf84a872cc24d73dd42d4e695d4b',
            vaultInitialParam: {
                tickLower: -15780,
                tickUpper: -13440,
                leverageWad: "150000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "500000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "100000000000000000",
                weight: "60",
            }
        },

        'rETH_v3': {
            marginEngine: '0x14e8470af507d46c7a1696c75a183a95bd8f5fe0',
            vaultInitialParam: {
                tickLower: -14640,
                tickUpper: -12000,
                leverageWad: "150000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "500000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "100000000000000000",
                weight: "20",
            }
        },

        'borrow_aETH_v3': {
            marginEngine: '0x107b152efc8900d8aa2cd45297c620d886558477',
            vaultInitialParam: {
                tickLower: -14820,
                tickUpper: -12240,
                leverageWad: "150000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "500000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "100000000000000000",
                weight: "20",
            }
        },

        // USDT
        'borrow_cUSDT_v2': {
            marginEngine: '0x5eaa5ff3a0a7c982715feb768be143461fdd4de9',
            vaultInitialParam: {
                tickLower: -15780,
                tickUpper: -13440,
                leverageWad: "80000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "500000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "100000000000000000",
                weight: "50",
            }
        },

        'borrow_aUSDT_v2': {
            marginEngine: '0x1e2f114b6948946a42574a953dcb7838b2c810ea',
            vaultInitialParam: {
                tickLower: -12840,
                tickUpper: -9540,
                leverageWad: "80000000000000000000",
                marginMultiplierPostUnwindWad: "2000000000000000000",
            },
            vaultStrategyParam: {
                sigmaWad: "500000000000000000",
                maxPossibleLowerBoundWad: "10000000000000000000",
                proximityWad: "100000000000000000",
                weight: "50",
            }
        },
    }
}

task("generateVoltzDeployments", "Voltz Vault Deployments")
    .setAction(
        async (_, hre) => {
            const network = hre.network.name;
            if (!(network === 'mainnet')) {
                throw new Error("This multisig setup is specific to mainnet");
            }
            const networkSetup = setup['mainnet'];

            const { deployments, getNamedAccounts } = hre;
            const { read } = deployments;

            const { voltzMultisig, usdc, dai, usdt, weth } =
                await getNamedAccounts();

            const getTokenPadding = (token: string): string => {
                switch (token) {
                    case usdc: {
                        return "000000";
                    }
                    case usdt: {
                        return "000000";
                    }
                    case weth: {
                        return "000000000000000000";
                    }
                    case dai: {
                        return "000000000000000000";
                    }
                    default: {
                        throw new Error("Invalid token");
                    }
                }
            }

            const getPredictedAddress = async(from: string, implementationContractAddress: string): Promise<string> => {
                const salt = "0x".concat(stripHexPrefix(hre.ethers.utils.hexValue(nft)).padStart(64, "0"));
            
                const implementation = stripHexPrefix(implementationContractAddress.toLowerCase()).padStart(40, "0");
                const initCode = `0x3d602d80600a3d3981f3363d3d373d3d3d363d73${implementation}5af43d82803e903d91602b57fd5bf3`;
                const initCodeHash = hre.ethers.utils.keccak256(initCode);
            
                return hre.ethers.utils.getCreate2Address(from, salt, initCodeHash);
            }

            // Get the general addresses
            const voltzVaultHelper = (await hre.ethers.getContract("VoltzVaultHelper")).address;
            const voltzVaultGovernance = (await hre.ethers.getContract("VoltzVaultGovernance")).address;
            const erc20VaultGovernance = (await hre.ethers.getContract("ERC20VaultGovernance")).address;
            const erc20RootVaultGovernance = (await hre.ethers.getContract("ERC20RootVaultGovernance")).address;
            const masterStrategy = (await hre.ethers.getContract("LPOptimiserStrategy")).address;
            const vaultRegistry = (await hre.ethers.getContract("VaultRegistry")).address;

            // Track changing states
            let masterStrategyNonce = Math.max(await hre.ethers.provider.getTransactionCount(masterStrategy), 1);
            let nft = (await read("VaultRegistry", "vaultsCount")).toNumber() + 1;

            // Set the deployment parameters

            const vaultSets: {
                voltzPools: string[];
                VAULT_CAP: number;
                token: string;
            }[] = [
                    {
                        voltzPools: ['aUSDC_v12' , 'borrow_aUSDC_v2'],
                        VAULT_CAP: 10000000, // USDC
                        token: usdc,
                    },
                    {
                        voltzPools: ['stETH_v3' , 'rETH_v3', 'borrow_aETH_v3'],
                        VAULT_CAP: 6000, // ETH
                        token: weth,
                    },
                    {
                        voltzPools: ['borrow_cUSDT_v2' , 'borrow_aUSDT_v2'],
                        VAULT_CAP: 10000000, // USDT
                        token: usdt,
                    },
                ];

            const data: voltzTemplateData = {
                data: [],
                owner: voltzMultisig,
                vaultRegistry,
                voltzVaultGovernance,
                erc20VaultGovernance,
                erc20RootVaultGovernance,
                masterStrategy,
                voltzVaultHelperSingleton: voltzVaultHelper,
                rebalancer: "0x4f8904c34bd86fd674c17fac3c5db32485aff69c",
            };

            // Build the deployment parameters
            for (let setIndex = 0; setIndex < vaultSets.length; setIndex++) {
                const { voltzPools, VAULT_CAP, token } = vaultSets[setIndex];
                const vaultCap = (VAULT_CAP.toString()).concat(getTokenPadding(token));

                // Get the next N NFTs for Voltz vaults (each vault is represented as an nft)
                // within the vault registry, keep track of all the vaults deployed in mellow
                const voltzVaultNFTs: number[] = [];
                const voltzVaultAddresses: string[] = [];
                for (let i = 0; i < voltzPools.length; i++) {
                    voltzVaultNFTs.push(nft);

                    const predictedVoltzVaultAddress = await getPredictedAddress(voltzVaultGovernance, (await hre.ethers.getContract("VoltzVault")).address);

                    nft++;
                    voltzVaultAddresses.push(predictedVoltzVaultAddress);
                }

                // Get the next NFT and address for ERC20 vault
                const erc20VaultNFT = nft;
                const erc20VaultAddress = await getPredictedAddress(erc20VaultGovernance, (await hre.ethers.getContract("ERC20Vault")).address);
                nft++;

                // Get the address of the strategy
                const strategy = hre.ethers.utils.getContractAddress({
                    from: masterStrategy,
                    nonce: masterStrategyNonce++,
                });

                // Get the next NFT for ERC20 Root vault
                const erc20RootVaultNFT = nft;
                nft++;

                const singularData: voltzTemplateDataSingular = {
                    voltzVaults: voltzPools.map(
                        (voltzVault: string) => {
                            return {
                                marginEngine: networkSetup[voltzVault].marginEngine,
                                initializeParams: networkSetup[voltzVault].vaultInitialParam
                            }

                        }
                    ),
                    token,
                    strategy,
                    erc20VaultAddress,
                    voltzVaultAddresses: voltzVaultAddresses.map((item, index) => {
                        return {
                            address: item,
                            last: (index + 1 === voltzVaultAddresses.length),
                        }
                    }),
                    vaultStrategyParams: voltzPools.map(
                        (item, index) => {
                            return {
                                params: networkSetup[item].vaultStrategyParam,
                                last: (index + 1 === voltzPools.length),
                            };
                        }
                    ),
                    vaultNFTs: [erc20VaultNFT].concat(voltzVaultNFTs).map(
                        (item, index) => {
                            return {
                                tokenId: item,
                                last: (index + 1 === [erc20VaultNFT].concat(voltzVaultNFTs).length),
                            };
                        }
                    ),
                    erc20RootVaultNFT,
                    vaultCap,
                };

                data.data.push({
                    vaultData: singularData,
                    last: (setIndex + 1 === vaultSets.length),
                });
            }

            writeVoltzDeployments(data);
        }
    )

